// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Actions': string;
  'Background': string;
  'Content': string;
  'Header': string;
  'Img': string;
  'Info': string;
  'Name': string;
  'NavButton': string;
  'Overlay': string;
  'Preview': string;
  'PreviewContainer': string;
  'TransparentImg': string;
}
export const cssExports: CssExports;
export default cssExports;
